### ISSUE TITLE
Help does not display sub command

### ISSUE THREAD

**Issue by ruudk** [thatisuday/commando#6]
Looking at the example from the [readme](https://github.com/thatisuday/commando#usage-of-the-sub-command) I noticed that Commando doesn't display the correct information.

It shows the red one, but I expected to see the green one:
```diff
 $ reactor create -h
 
 This command creates a component of a given type and outputs component files in the project directory.
 
 Usage:
-  reactor <name> [version] [files] {flags}
+  reactor create <name> [version] [files] {flags}
```

**Comment by niaxi** [comment]
There is a PR for this: https://github.com/thatisuday/commando/pull/11

Consider upvoting that PR - might help get it merged in.
